class Countries {
  static const List<Map<String, String>> all = [
    {
      'ar': 'السعودية',
      'en': 'Saudi Arabia',
      'code': '+966',
      'flag': '🇸🇦',
      'digits': '9',
    },
    {'ar': 'مصر', 'en': 'Egypt', 'code': '+20', 'flag': '🇪🇬', 'digits': '10'},
    {
      'ar': 'الإمارات',
      'en': 'UAE',
      'code': '+971',
      'flag': '🇦🇪',
      'digits': '9',
    },
    {
      'ar': 'الكويت',
      'en': 'Kuwait',
      'code': '+965',
      'flag': '🇰🇼',
      'digits': '8',
    },
    {'ar': 'قطر', 'en': 'Qatar', 'code': '+974', 'flag': '🇶🇦', 'digits': '8'},
    {
      'ar': 'البحرين',
      'en': 'Bahrain',
      'code': '+973',
      'flag': '🇧🇭',
      'digits': '8',
    },
    {
      'ar': 'عُمان',
      'en': 'Oman',
      'code': '+968',
      'flag': '🇴🇲',
      'digits': '8',
    },
    {
      'ar': 'الأردن',
      'en': 'Jordan',
      'code': '+962',
      'flag': '🇯🇴',
      'digits': '9',
    },
    {
      'ar': 'لبنان',
      'en': 'Lebanon',
      'code': '+961',
      'flag': '🇱🇧',
      'digits': '8',
    },
    {
      'ar': 'العراق',
      'en': 'Iraq',
      'code': '+964',
      'flag': '🇮🇶',
      'digits': '10',
    },
    {
      'ar': 'سوريا',
      'en': 'Syria',
      'code': '+963',
      'flag': '🇸🇾',
      'digits': '9',
    },
    {
      'ar': 'اليمن',
      'en': 'Yemen',
      'code': '+967',
      'flag': '🇾🇪',
      'digits': '9',
    },
    {
      'ar': 'ليبيا',
      'en': 'Libya',
      'code': '+218',
      'flag': '🇱🇾',
      'digits': '9',
    },
    {
      'ar': 'تونس',
      'en': 'Tunisia',
      'code': '+216',
      'flag': '🇹🇳',
      'digits': '8',
    },
    {
      'ar': 'الجزائر',
      'en': 'Algeria',
      'code': '+213',
      'flag': '🇩🇿',
      'digits': '9',
    },
    {
      'ar': 'المغرب',
      'en': 'Morocco',
      'code': '+212',
      'flag': '🇲🇦',
      'digits': '9',
    },
    {
      'ar': 'موريتانيا',
      'en': 'Mauritania',
      'code': '+222',
      'flag': '🇲🇷',
      'digits': '8',
    },
    {
      'ar': 'السودان',
      'en': 'Sudan',
      'code': '+249',
      'flag': '🇸🇩',
      'digits': '9',
    },
    {
      'ar': 'الصومال',
      'en': 'Somalia',
      'code': '+252',
      'flag': '🇸🇴',
      'digits': '8',
    },
    {
      'ar': 'جيبوتي',
      'en': 'Djibouti',
      'code': '+253',
      'flag': '🇩🇯',
      'digits': '8',
    },
    {
      'ar': 'جزر القمر',
      'en': 'Comoros',
      'code': '+269',
      'flag': '🇰🇲',
      'digits': '7',
    },
    {
      'ar': 'فلسطين',
      'en': 'Palestine',
      'code': '+970',
      'flag': '🇵🇸',
      'digits': '9',
    },
    {
      'ar': 'المملكة المتحدة',
      'en': 'United Kingdom',
      'code': '+44',
      'flag': '🇬🇧',
      'digits': '10',
    },
    {
      'ar': 'ألمانيا',
      'en': 'Germany',
      'code': '+49',
      'flag': '🇩🇪',
      'digits': '11',
    },
    {
      'ar': 'فرنسا',
      'en': 'France',
      'code': '+33',
      'flag': '🇫🇷',
      'digits': '9',
    },
    {
      'ar': 'إيطاليا',
      'en': 'Italy',
      'code': '+39',
      'flag': '🇮🇹',
      'digits': '10',
    },
    {
      'ar': 'إسبانيا',
      'en': 'Spain',
      'code': '+34',
      'flag': '🇪🇸',
      'digits': '9',
    },
    {
      'ar': 'البرتغال',
      'en': 'Portugal',
      'code': '+351',
      'flag': '🇵🇹',
      'digits': '9',
    },
    {
      'ar': 'هولندا',
      'en': 'Netherlands',
      'code': '+31',
      'flag': '🇳🇱',
      'digits': '9',
    },
    {
      'ar': 'بلجيكا',
      'en': 'Belgium',
      'code': '+32',
      'flag': '🇧🇪',
      'digits': '9',
    },
    {
      'ar': 'سويسرا',
      'en': 'Switzerland',
      'code': '+41',
      'flag': '🇨🇭',
      'digits': '9',
    },
    {
      'ar': 'النمسا',
      'en': 'Austria',
      'code': '+43',
      'flag': '🇦🇹',
      'digits': '10',
    },
    {
      'ar': 'السويد',
      'en': 'Sweden',
      'code': '+46',
      'flag': '🇸🇪',
      'digits': '9',
    },
    {
      'ar': 'النرويج',
      'en': 'Norway',
      'code': '+47',
      'flag': '🇳🇴',
      'digits': '8',
    },
    {
      'ar': 'الدنمارك',
      'en': 'Denmark',
      'code': '+45',
      'flag': '🇩🇰',
      'digits': '8',
    },
    {
      'ar': 'فنلندا',
      'en': 'Finland',
      'code': '+358',
      'flag': '🇫🇮',
      'digits': '9',
    },
    {
      'ar': 'بولندا',
      'en': 'Poland',
      'code': '+48',
      'flag': '🇵🇱',
      'digits': '9',
    },
    {
      'ar': 'التشيك',
      'en': 'Czech Republic',
      'code': '+420',
      'flag': '🇨🇿',
      'digits': '9',
    },
    {
      'ar': 'المجر',
      'en': 'Hungary',
      'code': '+36',
      'flag': '🇭🇺',
      'digits': '9',
    },
    {
      'ar': 'رومانيا',
      'en': 'Romania',
      'code': '+40',
      'flag': '🇷🇴',
      'digits': '9',
    },
    {
      'ar': 'اليونان',
      'en': 'Greece',
      'code': '+30',
      'flag': '🇬🇷',
      'digits': '10',
    },
    {
      'ar': 'تركيا',
      'en': 'Turkey',
      'code': '+90',
      'flag': '🇹🇷',
      'digits': '10',
    },
    {
      'ar': 'روسيا',
      'en': 'Russia',
      'code': '+7',
      'flag': '🇷🇺',
      'digits': '10',
    },
    {
      'ar': 'أوكرانيا',
      'en': 'Ukraine',
      'code': '+380',
      'flag': '🇺🇦',
      'digits': '9',
    },
    {
      'ar': 'كرواتيا',
      'en': 'Croatia',
      'code': '+385',
      'flag': '🇭🇷',
      'digits': '9',
    },
    {
      'ar': 'صربيا',
      'en': 'Serbia',
      'code': '+381',
      'flag': '🇷🇸',
      'digits': '9',
    },
    {
      'ar': 'سلوفاكيا',
      'en': 'Slovakia',
      'code': '+421',
      'flag': '🇸🇰',
      'digits': '9',
    },
    {
      'ar': 'بلغاريا',
      'en': 'Bulgaria',
      'code': '+359',
      'flag': '🇧🇬',
      'digits': '9',
    },
    {
      'ar': 'أيرلندا',
      'en': 'Ireland',
      'code': '+353',
      'flag': '🇮🇪',
      'digits': '9',
    },
    {
      'ar': 'لوكسمبورغ',
      'en': 'Luxembourg',
      'code': '+352',
      'flag': '🇱🇺',
      'digits': '9',
    },
    {
      'ar': 'أيسلندا',
      'en': 'Iceland',
      'code': '+354',
      'flag': '🇮🇸',
      'digits': '7',
    },
    {
      'ar': 'مالطا',
      'en': 'Malta',
      'code': '+356',
      'flag': '🇲🇹',
      'digits': '8',
    },
    {
      'ar': 'قبرص',
      'en': 'Cyprus',
      'code': '+357',
      'flag': '🇨🇾',
      'digits': '8',
    },
    {
      'ar': 'إستونيا',
      'en': 'Estonia',
      'code': '+372',
      'flag': '🇪🇪',
      'digits': '8',
    },
    {
      'ar': 'لاتفيا',
      'en': 'Latvia',
      'code': '+371',
      'flag': '🇱🇻',
      'digits': '8',
    },
    {
      'ar': 'ليتوانيا',
      'en': 'Lithuania',
      'code': '+370',
      'flag': '🇱🇹',
      'digits': '8',
    },
    {
      'ar': 'سلوفينيا',
      'en': 'Slovenia',
      'code': '+386',
      'flag': '🇸🇮',
      'digits': '8',
    },
    {
      'ar': 'ألبانيا',
      'en': 'Albania',
      'code': '+355',
      'flag': '🇦🇱',
      'digits': '9',
    },
    {
      'ar': 'مقدونيا الشمالية',
      'en': 'North Macedonia',
      'code': '+389',
      'flag': '🇲🇰',
      'digits': '8',
    },
    {
      'ar': 'البوسنة',
      'en': 'Bosnia',
      'code': '+387',
      'flag': '🇧🇦',
      'digits': '8',
    },
    {
      'ar': 'الجبل الأسود',
      'en': 'Montenegro',
      'code': '+382',
      'flag': '🇲🇪',
      'digits': '8',
    },
    {
      'ar': 'كوسوفو',
      'en': 'Kosovo',
      'code': '+383',
      'flag': '🇽🇰',
      'digits': '8',
    },
    {
      'ar': 'مولدوفا',
      'en': 'Moldova',
      'code': '+373',
      'flag': '🇲🇩',
      'digits': '8',
    },
    {
      'ar': 'بيلاروسيا',
      'en': 'Belarus',
      'code': '+375',
      'flag': '🇧🇾',
      'digits': '9',
    },
    {
      'ar': 'أندورا',
      'en': 'Andorra',
      'code': '+376',
      'flag': '🇦🇩',
      'digits': '6',
    },
    {
      'ar': 'موناكو',
      'en': 'Monaco',
      'code': '+377',
      'flag': '🇲🇨',
      'digits': '8',
    },
    {
      'ar': 'سان مارينو',
      'en': 'San Marino',
      'code': '+378',
      'flag': '🇸🇲',
      'digits': '8',
    },
    {
      'ar': 'ليختنشتاين',
      'en': 'Liechtenstein',
      'code': '+423',
      'flag': '🇱🇮',
      'digits': '7',
    },
    {
      'ar': 'الصين',
      'en': 'China',
      'code': '+86',
      'flag': '🇨🇳',
      'digits': '11',
    },
    {
      'ar': 'الهند',
      'en': 'India',
      'code': '+91',
      'flag': '🇮🇳',
      'digits': '10',
    },
    {
      'ar': 'اليابان',
      'en': 'Japan',
      'code': '+81',
      'flag': '🇯🇵',
      'digits': '10',
    },
    {
      'ar': 'كوريا الجنوبية',
      'en': 'South Korea',
      'code': '+82',
      'flag': '🇰🇷',
      'digits': '10',
    },
    {
      'ar': 'إندونيسيا',
      'en': 'Indonesia',
      'code': '+62',
      'flag': '🇮🇩',
      'digits': '11',
    },
    {
      'ar': 'ماليزيا',
      'en': 'Malaysia',
      'code': '+60',
      'flag': '🇲🇾',
      'digits': '9',
    },
    {
      'ar': 'سنغافورة',
      'en': 'Singapore',
      'code': '+65',
      'flag': '🇸🇬',
      'digits': '8',
    },
    {
      'ar': 'تايلاند',
      'en': 'Thailand',
      'code': '+66',
      'flag': '🇹🇭',
      'digits': '9',
    },
    {
      'ar': 'فيتنام',
      'en': 'Vietnam',
      'code': '+84',
      'flag': '🇻🇳',
      'digits': '9',
    },
    {
      'ar': 'الفلبين',
      'en': 'Philippines',
      'code': '+63',
      'flag': '🇵🇭',
      'digits': '10',
    },
    {
      'ar': 'باكستان',
      'en': 'Pakistan',
      'code': '+92',
      'flag': '🇵🇰',
      'digits': '10',
    },
    {
      'ar': 'بنغلاديش',
      'en': 'Bangladesh',
      'code': '+880',
      'flag': '🇧🇩',
      'digits': '10',
    },
    {
      'ar': 'سريلانكا',
      'en': 'Sri Lanka',
      'code': '+94',
      'flag': '🇱🇰',
      'digits': '9',
    },
    {
      'ar': 'نيبال',
      'en': 'Nepal',
      'code': '+977',
      'flag': '🇳🇵',
      'digits': '10',
    },
    {
      'ar': 'ميانمار',
      'en': 'Myanmar',
      'code': '+95',
      'flag': '🇲🇲',
      'digits': '9',
    },
    {
      'ar': 'كمبوديا',
      'en': 'Cambodia',
      'code': '+855',
      'flag': '🇰🇭',
      'digits': '9',
    },
    {'ar': 'لاوس', 'en': 'Laos', 'code': '+856', 'flag': '🇱🇦', 'digits': '9'},
    {
      'ar': 'إيران',
      'en': 'Iran',
      'code': '+98',
      'flag': '🇮🇷',
      'digits': '10',
    },
    {
      'ar': 'أفغانستان',
      'en': 'Afghanistan',
      'code': '+93',
      'flag': '🇦🇫',
      'digits': '9',
    },
    {
      'ar': 'كازاخستان',
      'en': 'Kazakhstan',
      'code': '+7',
      'flag': '🇰🇿',
      'digits': '10',
    },
    {
      'ar': 'أوزبكستان',
      'en': 'Uzbekistan',
      'code': '+998',
      'flag': '🇺🇿',
      'digits': '9',
    },
    {
      'ar': 'أذربيجان',
      'en': 'Azerbaijan',
      'code': '+994',
      'flag': '🇦🇿',
      'digits': '9',
    },
    {
      'ar': 'جورجيا',
      'en': 'Georgia',
      'code': '+995',
      'flag': '🇬🇪',
      'digits': '9',
    },
    {
      'ar': 'أرمينيا',
      'en': 'Armenia',
      'code': '+374',
      'flag': '🇦🇲',
      'digits': '8',
    },
    {
      'ar': 'طاجيكستان',
      'en': 'Tajikistan',
      'code': '+992',
      'flag': '🇹🇯',
      'digits': '9',
    },
    {
      'ar': 'تركمانستان',
      'en': 'Turkmenistan',
      'code': '+993',
      'flag': '🇹🇲',
      'digits': '8',
    },
    {
      'ar': 'قيرغيزستان',
      'en': 'Kyrgyzstan',
      'code': '+996',
      'flag': '🇰🇬',
      'digits': '9',
    },
    {
      'ar': 'منغوليا',
      'en': 'Mongolia',
      'code': '+976',
      'flag': '🇲🇳',
      'digits': '8',
    },
    {
      'ar': 'تايوان',
      'en': 'Taiwan',
      'code': '+886',
      'flag': '🇹🇼',
      'digits': '9',
    },
    {
      'ar': 'هونغ كونغ',
      'en': 'Hong Kong',
      'code': '+852',
      'flag': '🇭🇰',
      'digits': '8',
    },
    {
      'ar': 'ماكاو',
      'en': 'Macao',
      'code': '+853',
      'flag': '🇲🇴',
      'digits': '8',
    },
    {
      'ar': 'بروناي',
      'en': 'Brunei',
      'code': '+673',
      'flag': '🇧🇳',
      'digits': '7',
    },
    {
      'ar': 'تيمور الشرقية',
      'en': 'East Timor',
      'code': '+670',
      'flag': '🇹🇱',
      'digits': '8',
    },
    {
      'ar': 'المالديف',
      'en': 'Maldives',
      'code': '+960',
      'flag': '🇲🇻',
      'digits': '7',
    },
    {
      'ar': 'بوتان',
      'en': 'Bhutan',
      'code': '+975',
      'flag': '🇧🇹',
      'digits': '8',
    },
    {
      'ar': 'إسرائيل',
      'en': 'Israel',
      'code': '+972',
      'flag': '🇮🇱',
      'digits': '9',
    },
    {
      'ar': 'الولايات المتحدة',
      'en': 'United States',
      'code': '+1',
      'flag': '🇺🇸',
      'digits': '10',
    },
    {
      'ar': 'كندا',
      'en': 'Canada',
      'code': '+1',
      'flag': '🇨🇦',
      'digits': '10',
    },
    {
      'ar': 'المكسيك',
      'en': 'Mexico',
      'code': '+52',
      'flag': '🇲🇽',
      'digits': '10',
    },
    {'ar': 'كوبا', 'en': 'Cuba', 'code': '+53', 'flag': '🇨🇺', 'digits': '8'},
    {
      'ar': 'جامايكا',
      'en': 'Jamaica',
      'code': '+1876',
      'flag': '🇯🇲',
      'digits': '7',
    },
    {
      'ar': 'هايتي',
      'en': 'Haiti',
      'code': '+509',
      'flag': '🇭🇹',
      'digits': '8',
    },
    {
      'ar': 'جواتيمالا',
      'en': 'Guatemala',
      'code': '+502',
      'flag': '🇬🇹',
      'digits': '8',
    },
    {
      'ar': 'هندوراس',
      'en': 'Honduras',
      'code': '+504',
      'flag': '🇭🇳',
      'digits': '8',
    },
    {
      'ar': 'السلفادور',
      'en': 'El Salvador',
      'code': '+503',
      'flag': '🇸🇻',
      'digits': '8',
    },
    {
      'ar': 'نيكاراغوا',
      'en': 'Nicaragua',
      'code': '+505',
      'flag': '🇳🇮',
      'digits': '8',
    },
    {
      'ar': 'كوستاريكا',
      'en': 'Costa Rica',
      'code': '+506',
      'flag': '🇨🇷',
      'digits': '8',
    },
    {
      'ar': 'بنما',
      'en': 'Panama',
      'code': '+507',
      'flag': '🇵🇦',
      'digits': '8',
    },
    {
      'ar': 'بليز',
      'en': 'Belize',
      'code': '+501',
      'flag': '🇧🇿',
      'digits': '7',
    },
    {
      'ar': 'جمهورية الدومينيكان',
      'en': 'Dominican Republic',
      'code': '+1809',
      'flag': '🇩🇴',
      'digits': '7',
    },
    {
      'ar': 'ترينيداد وتوباغو',
      'en': 'Trinidad and Tobago',
      'code': '+1868',
      'flag': '🇹🇹',
      'digits': '7',
    },
    {
      'ar': 'باهاماس',
      'en': 'Bahamas',
      'code': '+1242',
      'flag': '🇧🇸',
      'digits': '7',
    },
    {
      'ar': 'باربادوس',
      'en': 'Barbados',
      'code': '+1246',
      'flag': '🇧🇧',
      'digits': '7',
    },
    {
      'ar': 'البرازيل',
      'en': 'Brazil',
      'code': '+55',
      'flag': '🇧🇷',
      'digits': '11',
    },
    {
      'ar': 'الأرجنتين',
      'en': 'Argentina',
      'code': '+54',
      'flag': '🇦🇷',
      'digits': '10',
    },
    {
      'ar': 'كولومبيا',
      'en': 'Colombia',
      'code': '+57',
      'flag': '🇨🇴',
      'digits': '10',
    },
    {
      'ar': 'تشيلي',
      'en': 'Chile',
      'code': '+56',
      'flag': '🇨🇱',
      'digits': '9',
    },
    {'ar': 'بيرو', 'en': 'Peru', 'code': '+51', 'flag': '🇵🇪', 'digits': '9'},
    {
      'ar': 'فنزويلا',
      'en': 'Venezuela',
      'code': '+58',
      'flag': '🇻🇪',
      'digits': '10',
    },
    {
      'ar': 'الإكوادور',
      'en': 'Ecuador',
      'code': '+593',
      'flag': '🇪🇨',
      'digits': '9',
    },
    {
      'ar': 'بوليفيا',
      'en': 'Bolivia',
      'code': '+591',
      'flag': '🇧🇴',
      'digits': '8',
    },
    {
      'ar': 'باراغواي',
      'en': 'Paraguay',
      'code': '+595',
      'flag': '🇵🇾',
      'digits': '9',
    },
    {
      'ar': 'أوروغواي',
      'en': 'Uruguay',
      'code': '+598',
      'flag': '🇺🇾',
      'digits': '8',
    },
    {
      'ar': 'غيانا',
      'en': 'Guyana',
      'code': '+592',
      'flag': '🇬🇾',
      'digits': '7',
    },
    {
      'ar': 'سورينام',
      'en': 'Suriname',
      'code': '+597',
      'flag': '🇸🇷',
      'digits': '7',
    },
    {
      'ar': 'نيجيريا',
      'en': 'Nigeria',
      'code': '+234',
      'flag': '🇳🇬',
      'digits': '10',
    },
    {
      'ar': 'إثيوبيا',
      'en': 'Ethiopia',
      'code': '+251',
      'flag': '🇪🇹',
      'digits': '9',
    },
    {
      'ar': 'كينيا',
      'en': 'Kenya',
      'code': '+254',
      'flag': '🇰🇪',
      'digits': '9',
    },
    {
      'ar': 'تنزانيا',
      'en': 'Tanzania',
      'code': '+255',
      'flag': '🇹🇿',
      'digits': '9',
    },
    {
      'ar': 'أوغندا',
      'en': 'Uganda',
      'code': '+256',
      'flag': '🇺🇬',
      'digits': '9',
    },
    {
      'ar': 'غانا',
      'en': 'Ghana',
      'code': '+233',
      'flag': '🇬🇭',
      'digits': '9',
    },
    {
      'ar': 'كوت ديفوار',
      'en': 'Ivory Coast',
      'code': '+225',
      'flag': '🇨🇮',
      'digits': '8',
    },
    {
      'ar': 'الكاميرون',
      'en': 'Cameroon',
      'code': '+237',
      'flag': '🇨🇲',
      'digits': '9',
    },
    {
      'ar': 'السنغال',
      'en': 'Senegal',
      'code': '+221',
      'flag': '🇸🇳',
      'digits': '9',
    },
    {
      'ar': 'زامبيا',
      'en': 'Zambia',
      'code': '+260',
      'flag': '🇿🇲',
      'digits': '9',
    },
    {
      'ar': 'زيمبابوي',
      'en': 'Zimbabwe',
      'code': '+263',
      'flag': '🇿🇼',
      'digits': '9',
    },
    {
      'ar': 'موزمبيق',
      'en': 'Mozambique',
      'code': '+258',
      'flag': '🇲🇿',
      'digits': '9',
    },
    {
      'ar': 'مدغشقر',
      'en': 'Madagascar',
      'code': '+261',
      'flag': '🇲🇬',
      'digits': '9',
    },
    {
      'ar': 'أنغولا',
      'en': 'Angola',
      'code': '+244',
      'flag': '🇦🇴',
      'digits': '9',
    },
    {
      'ar': 'رواندا',
      'en': 'Rwanda',
      'code': '+250',
      'flag': '🇷🇼',
      'digits': '9',
    },
    {
      'ar': 'بوروندي',
      'en': 'Burundi',
      'code': '+257',
      'flag': '🇧🇮',
      'digits': '8',
    },
    {'ar': 'مالي', 'en': 'Mali', 'code': '+223', 'flag': '🇲🇱', 'digits': '8'},
    {
      'ar': 'بوركينا فاسو',
      'en': 'Burkina Faso',
      'code': '+226',
      'flag': '🇧🇫',
      'digits': '8',
    },
    {
      'ar': 'النيجر',
      'en': 'Niger',
      'code': '+227',
      'flag': '🇳🇪',
      'digits': '8',
    },
    {'ar': 'تشاد', 'en': 'Chad', 'code': '+235', 'flag': '🇹🇩', 'digits': '8'},
    {
      'ar': 'جمهورية أفريقيا الوسطى',
      'en': 'Central African Republic',
      'code': '+236',
      'flag': '🇨🇫',
      'digits': '8',
    },
    {
      'ar': 'الكونغو',
      'en': 'Congo',
      'code': '+242',
      'flag': '🇨🇬',
      'digits': '9',
    },
    {
      'ar': 'الكونغو الديمقراطية',
      'en': 'DR Congo',
      'code': '+243',
      'flag': '🇨🇩',
      'digits': '9',
    },
    {
      'ar': 'غينيا',
      'en': 'Guinea',
      'code': '+224',
      'flag': '🇬🇳',
      'digits': '9',
    },
    {
      'ar': 'غينيا الاستوائية',
      'en': 'Equatorial Guinea',
      'code': '+240',
      'flag': '🇬🇶',
      'digits': '9',
    },
    {
      'ar': 'غينيا بيساو',
      'en': 'Guinea-Bissau',
      'code': '+245',
      'flag': '🇬🇼',
      'digits': '7',
    },
    {
      'ar': 'سيراليون',
      'en': 'Sierra Leone',
      'code': '+232',
      'flag': '🇸🇱',
      'digits': '8',
    },
    {
      'ar': 'ليبيريا',
      'en': 'Liberia',
      'code': '+231',
      'flag': '🇱🇷',
      'digits': '7',
    },
    {'ar': 'توغو', 'en': 'Togo', 'code': '+228', 'flag': '🇹🇬', 'digits': '8'},
    {
      'ar': 'بنين',
      'en': 'Benin',
      'code': '+229',
      'flag': '🇧🇯',
      'digits': '8',
    },
    {
      'ar': 'غامبيا',
      'en': 'Gambia',
      'code': '+220',
      'flag': '🇬🇲',
      'digits': '7',
    },
    {
      'ar': 'الرأس الأخضر',
      'en': 'Cape Verde',
      'code': '+238',
      'flag': '🇨🇻',
      'digits': '7',
    },
    {
      'ar': 'ساو تومي وبرينسيب',
      'en': 'São Tomé and Príncipe',
      'code': '+239',
      'flag': '🇸🇹',
      'digits': '7',
    },
    {
      'ar': 'إريتريا',
      'en': 'Eritrea',
      'code': '+291',
      'flag': '🇪🇷',
      'digits': '7',
    },
    {
      'ar': 'جنوب السودان',
      'en': 'South Sudan',
      'code': '+211',
      'flag': '🇸🇸',
      'digits': '9',
    },
    {
      'ar': 'ناميبيا',
      'en': 'Namibia',
      'code': '+264',
      'flag': '🇳🇦',
      'digits': '9',
    },
    {
      'ar': 'بوتسوانا',
      'en': 'Botswana',
      'code': '+267',
      'flag': '🇧🇼',
      'digits': '8',
    },
    {
      'ar': 'ليسوتو',
      'en': 'Lesotho',
      'code': '+266',
      'flag': '🇱🇸',
      'digits': '8',
    },
    {
      'ar': 'إسواتيني',
      'en': 'Eswatini',
      'code': '+268',
      'flag': '🇸🇿',
      'digits': '8',
    },
    {
      'ar': 'جنوب أفريقيا',
      'en': 'South Africa',
      'code': '+27',
      'flag': '🇿🇦',
      'digits': '9',
    },
    {
      'ar': 'مالاوي',
      'en': 'Malawi',
      'code': '+265',
      'flag': '🇲🇼',
      'digits': '9',
    },
    {
      'ar': 'سيشيل',
      'en': 'Seychelles',
      'code': '+248',
      'flag': '🇸🇨',
      'digits': '7',
    },
    {
      'ar': 'موريشيوس',
      'en': 'Mauritius',
      'code': '+230',
      'flag': '🇲🇺',
      'digits': '8',
    },
    {
      'ar': 'غابون',
      'en': 'Gabon',
      'code': '+241',
      'flag': '🇬🇦',
      'digits': '8',
    },
    {
      'ar': 'أستراليا',
      'en': 'Australia',
      'code': '+61',
      'flag': '🇦🇺',
      'digits': '9',
    },
    {
      'ar': 'نيوزيلندا',
      'en': 'New Zealand',
      'code': '+64',
      'flag': '🇳🇿',
      'digits': '9',
    },
    {'ar': 'فيجي', 'en': 'Fiji', 'code': '+679', 'flag': '🇫🇯', 'digits': '7'},
    {
      'ar': 'بابوا غينيا الجديدة',
      'en': 'Papua New Guinea',
      'code': '+675',
      'flag': '🇵🇬',
      'digits': '8',
    },
    {
      'ar': 'جزر سليمان',
      'en': 'Solomon Islands',
      'code': '+677',
      'flag': '🇸🇧',
      'digits': '7',
    },
    {
      'ar': 'فانواتو',
      'en': 'Vanuatu',
      'code': '+678',
      'flag': '🇻🇺',
      'digits': '7',
    },
    {
      'ar': 'ساموا',
      'en': 'Samoa',
      'code': '+685',
      'flag': '🇼🇸',
      'digits': '7',
    },
    {
      'ar': 'تونغا',
      'en': 'Tonga',
      'code': '+676',
      'flag': '🇹🇴',
      'digits': '7',
    },
    {
      'ar': 'كيريباس',
      'en': 'Kiribati',
      'code': '+686',
      'flag': '🇰🇮',
      'digits': '8',
    },
    {
      'ar': 'ميكرونيزيا',
      'en': 'Micronesia',
      'code': '+691',
      'flag': '🇫🇲',
      'digits': '7',
    },
    {
      'ar': 'جزر مارشال',
      'en': 'Marshall Islands',
      'code': '+692',
      'flag': '🇲🇭',
      'digits': '7',
    },
    {
      'ar': 'بالاو',
      'en': 'Palau',
      'code': '+680',
      'flag': '🇵🇼',
      'digits': '7',
    },
    {
      'ar': 'ناورو',
      'en': 'Nauru',
      'code': '+674',
      'flag': '🇳🇷',
      'digits': '7',
    },
    {
      'ar': 'توفالو',
      'en': 'Tuvalu',
      'code': '+688',
      'flag': '🇹🇻',
      'digits': '6',
    },
  ];
}
