// File generated by FlutterFire CLI.
// Keys are loaded from --dart-define at build time via AppEnv.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:fitness_day/core/constant/app_env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: AppEnv.firebaseWebApiKey,
    appId: '1:308069649363:web:10485a0eb9319d9abe7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    authDomain: 'fitness-day-52c77.firebaseapp.com',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    measurementId: 'G-T8NGG1WR1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AppEnv.firebaseAndroidApiKey,
    appId: '1:308069649363:android:3f65e98e687b15ddbe7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: AppEnv.firebaseIosApiKey,
    appId: '1:308069649363:ios:82f5d10ccd2f7e40be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    iosBundleId: 'com.example.fitnessDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: AppEnv.firebaseIosApiKey,
    appId: '1:308069649363:ios:82f5d10ccd2f7e40be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    iosBundleId: 'com.example.fitnessDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: AppEnv.firebaseWebApiKey,
    appId: '1:308069649363:web:f4b054182e497f72be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    authDomain: 'fitness-day-52c77.firebaseapp.com',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    measurementId: 'G-WVXCZESR6P',
  );
}
