// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5jlApW04pIdUN85nprwddB5FNIHSKrlg',
    appId: '1:308069649363:web:10485a0eb9319d9abe7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    authDomain: 'fitness-day-52c77.firebaseapp.com',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    measurementId: 'G-T8NGG1WR1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg3UVoZ0axp0Ut3dNRXsKQOajnh1BtnXE',
    appId: '1:308069649363:android:3f65e98e687b15ddbe7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYaaKbX6Jbhtzvy6bDf5qeP1IRpSUcJHU',
    appId: '1:308069649363:ios:82f5d10ccd2f7e40be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    iosBundleId: 'com.example.fitnessDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYaaKbX6Jbhtzvy6bDf5qeP1IRpSUcJHU',
    appId: '1:308069649363:ios:82f5d10ccd2f7e40be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    iosBundleId: 'com.example.fitnessDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5jlApW04pIdUN85nprwddB5FNIHSKrlg',
    appId: '1:308069649363:web:f4b054182e497f72be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    authDomain: 'fitness-day-52c77.firebaseapp.com',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    measurementId: 'G-WVXCZESR6P',
  );
}
