// File generated by FlutterFire CLI.
// Keys are loaded from --dart-define at build time via AppEnv.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:fitness_day/core/constant/app_env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: AppEnv.firebaseWebApiKey.isEmpty
        ? 'AIzaSyBg3UVoZ0axp0Ut3dNRXsKQOajnh1BtnXE' // Fallback to Android key
        : AppEnv.firebaseWebApiKey,
    appId: '1:308069649363:web:10485a0eb9319d9abe7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    authDomain: 'fitness-day-52c77.firebaseapp.com',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    measurementId: 'G-T8NGG1WR1J',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: AppEnv.firebaseAndroidApiKey.isEmpty
        ? 'AIzaSyBg3UVoZ0axp0Ut3dNRXsKQOajnh1BtnXE' // From google-services.json
        : AppEnv.firebaseAndroidApiKey,
    appId:
        '1:308069649363:android:8fa51e989be0be6dbe7d26', // Updated to match google-services.json
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: AppEnv.firebaseIosApiKey.isEmpty
        ? 'AIzaSyDYaaKbX6Jbhtzvy6bDf5qeP1IRpSUcJHU' // From GoogleService-Info.plist
        : AppEnv.firebaseIosApiKey,
    appId:
        '1:308069649363:ios:2f637aa1ce2d9132be7d26', // Updated to match GoogleService-Info.plist
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    iosBundleId:
        'com.athr.fitnessday', // Updated to match GoogleService-Info.plist
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: AppEnv.firebaseIosApiKey.isEmpty
        ? 'AIzaSyDYaaKbX6Jbhtzvy6bDf5qeP1IRpSUcJHU' // From GoogleService-Info.plist
        : AppEnv.firebaseIosApiKey,
    appId:
        '1:308069649363:ios:2f637aa1ce2d9132be7d26', // Updated to match GoogleService-Info.plist
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    iosBundleId:
        'com.athr.fitnessday', // Updated to match GoogleService-Info.plist
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: AppEnv.firebaseWebApiKey.isEmpty
        ? 'AIzaSyBg3UVoZ0axp0Ut3dNRXsKQOajnh1BtnXE' // Fallback to Android key
        : AppEnv.firebaseWebApiKey,
    appId: '1:308069649363:web:f4b054182e497f72be7d26',
    messagingSenderId: '308069649363',
    projectId: 'fitness-day-52c77',
    authDomain: 'fitness-day-52c77.firebaseapp.com',
    storageBucket: 'fitness-day-52c77.firebasestorage.app',
    measurementId: 'G-WVXCZESR6P',
  );
}
